## 다층 Perceptron XOR Gate 학습(Activation Function Sigmoid 포함)

**Wt+1=Wt −𝛼∇𝐿(𝑊𝑡) 공식을 이용해서 weight와 bias 학습**

![2 input, 1 output 학습](XOR_Gate.png)

**1. Training Set X,Y 설정**

In [1]:
import numpy as np
# 1. 데이터 준비 (XOR 문제)
# 입력 데이터: [x1, x2]
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# 정답(Target) 데이터 (XOR 결과)
y = np.array([[0],
              [1],
              [1],
              [0]])

**2. Hypter Parameter 설정(learning rate, epochs 등)**

In [2]:
# 실험의 재현성을 위해 시드 고정
np.random.seed(42)

# 2. 가중치(Weights)와 편향(Biases) 초기화
# 은닉층 노드는 2개이므로 (입력층 노드 2 -> 은닉층 노드 2) 개수만큼 가중치와 편향 생성
# (이 두 개의 은닉 노드가 각각 NAND와 OR의 역할을 하도록 학습될 것입니다)
W1 = np.random.uniform(-1, 1, size=(2, 2))
b1 = np.random.uniform(-1, 1, size=(1, 2))

# 출력층 노드는 1개이므로 (은닉층 노드 2 -> 출력층 노드 1) 개수만큼 가중치와 편향 생성
# (은닉층의 두 출력을 취합받아 AND 연산 형태로 최종 결과를 만듭니다)
W2 = np.random.uniform(-1, 1, size=(2, 1))
b2 = np.random.uniform(-1, 1, size=(1, 1))

# 하이퍼파라미터 설정
epochs = 20000        # 학습(반복) 횟수
learning_rate = 0.5   # 학습률

In [3]:
W1

array([[-0.25091976,  0.90142861],
       [ 0.46398788,  0.19731697]])

In [4]:
W1.T

array([[-0.25091976,  0.46398788],
       [ 0.90142861,  0.19731697]])

**3. 출력 예측 함수 작성**

In [7]:
# 활성화 함수 (시그모이드 함수)
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 시그모이드 함수의 미분 (역전파시 기울기 계산에 사용)
def sigmoid_derivative(x):
    return x * (1 - x)

def predict(inputs):
    """출력 예측"""
    # [순전파 (Forward Propagation)]
    # 은닉층 (Hidden Layer): 입력값에 가중치를 곱하고 편향을 더한 후 활성화 함수 통과

    
    # 출력층 (Output Layer): 은닉층 결과를 입력으로 받아 동일하게 처리

    return hidden_layer_output,predicted_output

**4. (출력-타겟) 오차를 계산하고 weight_new=weight_old - 학습률x error x 활성함수 미분 x 입력 공식으로 weight 업데이트**

In [8]:
print("=========================")
print("  XOR 신경망 학습 시작   ")
print("=========================")

# 3. 모델 학습 (순전파 및 역전파)
for epoch in range(epochs + 1):
    hidden_layer_output,predicted_output=predict(X)    
    # [오차 계산]
 
    
    # [역전파 (Backpropagation)]
    # 출력층에서의 기울기 계산

    
    # 은닉층으로 오차 역전파 및 은닉층 기울기 계산

    
    # [가중치 및 편향 업데이트]

    
    # 진행 상황 출력 (2000 에포크마다)



  XOR 신경망 학습 시작   
Epoch:      0 | 손실(Loss): 0.25449
Epoch:   2000 | 손실(Loss): 0.00339
Epoch:   4000 | 손실(Loss): 0.00101
Epoch:   6000 | 손실(Loss): 0.00058
Epoch:   8000 | 손실(Loss): 0.00040
Epoch:  10000 | 손실(Loss): 0.00031
Epoch:  12000 | 손실(Loss): 0.00025
Epoch:  14000 | 손실(Loss): 0.00021
Epoch:  16000 | 손실(Loss): 0.00018
Epoch:  18000 | 손실(Loss): 0.00016
Epoch:  20000 | 손실(Loss): 0.00014


**5. 학습 결과 검증**

In [9]:
print("\n=========================")
print("       학습 완료!        ")
print("=========================\n")

# 4. 결과 확인
print("1. 입력 X:")
print(X)

print("\n2. 은닉층의 결과값 (NAND, OR 게이트 역할 지표):")
# 보통 하나는 NAND, 하나는 OR 형태와 근사한 출력을 뱉도록 최적화됩니다.
print(np.round(hidden_layer_output, 3))

print("\n3. 최종 출력 결과값 (AND 게이트 결합 효과 / 결과 확인):")
print(predicted_output)

print("\n4. 0과 1로 반올림한 최종 예측값:")
print(np.round(predicted_output))



       학습 완료!        

1. 입력 X:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

2. 은닉층의 결과값 (NAND, OR 게이트 역할 지표):
[[0.001 0.05 ]
 [0.067 0.974]
 [0.067 0.974]
 [0.909 1.   ]]

3. 최종 출력 결과값 (AND 게이트 결합 효과 / 결과 확인):
[[0.01307919]
 [0.98881518]
 [0.98881626]
 [0.01147946]]

4. 0과 1로 반올림한 최종 예측값:
[[0.]
 [1.]
 [1.]
 [0.]]
